### ISSUE TITLE
Product Category: Feature #2 needs style adjustments

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#101]
- [x] The copy should be same font color, size and line height as ``p`` at the top of the page
- [x] 'The Perfect Solution for' should be all capps
- [x] Add padding below 'The Perfect...' title to separate from the tags
- [x] View Details CTA should have same rounded corners as all other CTAs

![feature-2-styles](https://cloud.githubusercontent.com/assets/10550484/7078308/c465286c-decc-11e4-821b-b7b6ab934528.png)

**Comment by nickpaventi** [comment]
Changed line 14982 for the color line height and font-size.

**Comment by nickpaventi** [comment]
Added line 15074

.product-problem-links label {
  text-transform:uppercase;
}

**Comment by nickpaventi** [comment]
Added line 15068 for border-radius

**Comment by zheindel** [comment]
Hi @nickpaventi this still seems to be an issue here:  
http://dev.culligandiy.com/Whole-House-Systems

It seems like when you refresh it goes to the correct place and I also messed with my screen/window size and that helped but @mikewestaz was seeing the same issue
![screen shot 2015-04-13 at 4 12 21 pm](https://cloud.githubusercontent.com/assets/11874973/7127418/e1c6682e-e1f8-11e4-8639-be6e4c831533.png)

**Comment by nickpaventi** [comment]
@zheindel @mikewestaz this is related to some javascript that is under construction for the mobile na. Will check back once that is complete.

**Comment by nickpaventi** [comment]
@zheindel @mikewestaz can you test this again and see if you can reproduce it?

**Comment by zheindel** [comment]
Tried to reproduce and looks good.  Nice work!
