### ISSUE TITLE
Product Category [Tablet]: Product listing needs adjustments

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#102]
At 1024 view
- [x] Need to add padding between end of feature and beginning of product row
- [x] Product listing row should be updated to match functionality seen on homepage (http://dev.culligandiy.com/)

![screenshot 2015-04-09 15 29 58](https://cloud.githubusercontent.com/assets/10550484/7078394/7d87c8cc-decd-11e4-8a08-9d73d63f818e.png)

**Comment by nickpaventi** [comment]
Part 2 will be fixed via #63

**Comment by nickpaventi** [comment]
Fixed
