### ISSUE TITLE
Product Category [Desktop]: Longer sub-category menu solution needed

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#106]
Example: http://dev.culligandiy.com/Replacements

- [ ] Need to adjust the names of these sub-categories to fit on one line or find another solution 
- [ ] Suggestion: Rename all to '*Section* Replacements' instead of '*Section* Filters & Parts' 

Thoughts @zheindel ?
cc @nickpaventi 

![screenshot 2015-04-09 15 58 25](https://cloud.githubusercontent.com/assets/10550484/7078809/b0b1610a-ded1-11e4-8f8e-4ec576f8b889.png)

**Comment by zheindel** [comment]
@mikewestaz I agree to replace that to "Replacements" where it says "Filters & Parts"

**Comment by nickpaventi** [comment]
@zheindel this should be a change in the CMS, can you handle or reassign?

**Comment by zheindel** [comment]
@MartyBeckers I can't seem to find where you change the name of subcategory, Can you help us out with that.. with the Subcategories we just want to shorten it where it says "Filters and Parts" for example Undersink System Replacements same for the other categories there.

**Comment by MartyBeckers** [comment]
Yes I changed them and for future reference the categories, subcategories, and problem tags can all be changed at http://dev.culligandiy.com/cmsdesk/ > Administration > Categories.
