### ISSUE TITLE
Product Detail [Desktop]: Needs attention

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#107]
Sample page: http://dev.culligandiy.com/Replacements/Under-Sink-Systems/3-Stage-Ultrafiltration-Drinking-Water-Replacement
Comp: http://invis.io/BT2ETVL9Q

@zheindel @nickpaventi there's **a lot** of issues here. Please review and let me know if you have questions. 

- [ ] **I can't find any exclusive Lowes products to be able to test the display differences needed on this page. Has this been implemented?**
- [ ] **I can't find products that have thumbnail images/alternate shots or video, has this been implemented?**
- [ ] **I can't find products that have specs, has this been implemented?**
- [x] Use the new transparent product images sized to 500x500 Connie provided
- [x] Image space on desktop should be constrained to 450x450
- [x] Description copy should be the same styles as the copy applied to the category pages (screen shot below)
- [x] Missing 'Find a Retailer' button is missing completely (should either say "Find a Lowes Near You" or "Find a Retailer Near You" depending on product availability)
- [x] If it's a Lowes exclusive product, the logo and additional messaging should be present from comp
- [x] Easy Installation and no tools should not be an image, should be text and icons. Needs to be editable Culling per-product
- [x] The great box and the buttons inside it are wider than the comp, can we reduce this width?
- [x] 'Buy it from a dealer' should not link to the list of retailers on DIY, this should go to http://www.culligan.com/en-us/d/appointment/schedule-an-appointment/
- [x] Product tile line height is currently 52, should be ``line-height: 62px;``
- [x] The tags to the right of 'perfect solution...' should use the rest of the width of the width of the page 
- [x] Bullets under features and benefits are 18px, should be ``font-size: 16px;``
- [x] Missing the full-width blue bar for find a retailer (should either say "Find a Lowes Near You" or "Find a Retailer Near You" depending on product availability)
- [x] If Culligan is not providing additional product photography for the left of the features and benefits, we should remove the image, left justify Features and Benefits on the page (6 col) and make Specs on the right where applicable (6 col)
- [x] The wider/2-up product display is not consistent with the comps (image on left side, etc.)
- [x] **CHANGE FROM COMP** Need to add a mask over the background image, screen shot of updated comp attached
- [x] Find a Retailer CTA (and content below it) should be in-line horizontally with the top of the product name text

![screenshot 2015-04-09 16 16 06](https://cloud.githubusercontent.com/assets/10550484/7078984/c5174644-ded3-11e4-9ad1-51acabe45c6e.png)

![screenshot 2015-04-09 16 45 34](https://cloud.githubusercontent.com/assets/10550484/7079342/e1f9b68a-ded7-11e4-9a7a-de43b1962f90.png)

![pdp-part-1](https://cloud.githubusercontent.com/assets/10550484/7079145/c9676e7a-ded5-11e4-8c4d-4ac10a20ce61.png)

![pdp-02](https://cloud.githubusercontent.com/assets/10550484/7079244/b3720e3a-ded6-11e4-85f0-d6374b1b09fe.png)

![pdp-03](https://cloud.githubusercontent.com/assets/10550484/7079267/062ed82e-ded7-11e4-8be2-2da9f8cb75b0.png)

**Comment by zheindel** [comment]
@mikewestaz  I just messaged @MartyBeckers I don't think we can view any of the Lowe's products that were added.  Can you take a look at this, I sent you an email on this just a few minutes ago.

**Comment by MartyBeckers** [comment]
No Lowe's products have been added yet, but as soon as they are, the Lowe's panels will automatically display.  For an example of a product with placeholder images and a video, you can refer to http://dev.culligandiy.com/Shower-Head-Filters/Wall-Mount/RainDisc-Filtered-Showerhead

**Comment by mikewestaz** [comment]
Thanks @MartyBeckers - some of the issues noted above specifically apply to the non-lowes products. The CTA and bar+CTA that you mentioned should still be in the page for the Non-Lowes products, with different verbiage and no Lowes badging. 

Should we get on a quick call to discuss or do the items above make sense?
Example: *Missing the full-width blue bar for find a retailer (should either say "Find a Lowes Near You" or "Find a Retailer Near You" depending on product availability)*

cc @nickpaventi @zheindel

**Comment by MartyBeckers** [comment]
Ahh ok, in that case we'll need to make some back-end changes to the templates.  If you can send a quick mockup showing how each panel should look for non-Lowe's products, I can put that in place.

**Comment by mikewestaz** [comment]
@MartyBeckers 
Couple screen shots below show the two areas w/ copy and branding changes...

![screenshot 2015-04-09 17 09 01](https://cloud.githubusercontent.com/assets/10550484/7079609/226b3d3a-dedb-11e4-862f-2d4a467d2be1.png)

![screenshot 2015-04-09 17 09 40](https://cloud.githubusercontent.com/assets/10550484/7079625/549a70fa-dedb-11e4-9101-dbde902cc443.png)

cc @nickpaventi @zheindel

**Comment by MartyBeckers** [comment]
Perfect - and I'm assuming "Find a Retailer Near You" should go to http://dev.culligandiy.com/find-a-retailer/, but where should "buy it from a dealer" go to?

**Comment by mikewestaz** [comment]
@MartyBeckers Correct, please link the other to http://www.culligan.com/en-us/d/explore-my-state/

**Comment by mikewestaz** [comment]
@MartyBeckers **CORRECTION** LINK TO : http://www.culligan.com/en-us/d/appointment/schedule-an-appointment/

**Comment by MartyBeckers** [comment]
Ok the "Find a Retailer Near You" changes are in place.  Regarding the "Easy Installation" note, that's a true/false checkbox that we migrated from the original Ektron site.  Essentially a product is either easy to install or its not (showing or hiding that image), so if we were to make it editable text per product, I don't think it would ever be different.

**Comment by mikewestaz** [comment]
@MartyBeckers - Understood on the back-end part. If @zheindel is good there from the client POV I've go no concerns.

@nickpaventi I do believe this should be text and icons if possible or at least an SVG for best look on mobile, etc.

**Comment by zheindel** [comment]
@mikewestaz all good from the clients side!

Z

**Comment by yuchentai** [comment]
@MartyBeckers 
I couldn't find "perfect solution" section on Dev. Do you know where is it located? However, I pushed changes to git to extend the column width of the tags. Thanks

**Comment by MartyBeckers** [comment]
That's located at http://dev.culligandiy.com/CMSSiteManager/ > Page templates > Culligan DIY > Culligan DIY Product Detail > Design > sprocket next to "Detail Panel" > "Edit" next to "cmsproduct.culligan.detailpanel"

**Comment by nickpaventi** [comment]
@mikewestaz please take a look and see which of these items were completed by Marty

**Comment by mikewestaz** [comment]
@nickpaventi Closed the issues @MartyBeckers updates resolved

**Comment by nickpaventi** [comment]
@MartyBeckers can you take a look at the image /culliganDIY/media/img/product-detail/small-splash.jpg and change the extension to .png?

**Comment by nickpaventi** [comment]
@MartyBeckers if I am reading this correctly - If Culligan is not providing additional product photography for the left of the features and benefits, we should remove the image, left justify Features and Benefits on the page (6 col) and make Specs on the right where applicable (6 col)

Then I will need the following changes to the HTML

OLD
```HTML
<div class="row features-row" style="background-image: url("../../culligandiy/media/img/product-detail/spec-image.png?width=549&height=448&ext=.png");">
   <div class="columns small-12 medium-5 medium-offset-7 features-benefits">
      <h2 class="hide-for-small">Features & benefits</h2>
```
NEW
```HTML
<div class="row features-row">
  <div class="columns small-12 features-benefits">
    <div class="row">
       <div class="columns small-12 medium-6">
	  <h2 class="hide-for-small">Features &amp; benefits</h2>
	     <ul>
	     ...
             </ul>
       </div>
       <div class="columns small-12 medium-6">
	   <table>
	   ...
	   </table>
       </div>
      </div>	
   </div>
</div>

```

**Comment by nickpaventi** [comment]
@MartyBeckers is this in your logic?  If it's a Lowes exclusive product, the logo and additional messaging should be present from comp

**Comment by nickpaventi** [comment]
@MartyBeckers can you make the following HTML update for this part - The great box and the buttons inside it are wider than the comp, can we reduce this width?

Just moving the 2 anchor tags  inside the div class="warranty"...

OLD
```HTML
<div class="sidebar-product-manual-container">
                        <div class="row">
                            <div class="columns">
                                <div class="warranty">2-year limited warranty</div>
                                <a target="_blank" href="/getattachment/83119dfc-9adf-4955-bdb0-cd85eff876ed/attachment.aspx" class="button primary expand manual-button"><i class="fa fa-book"></i>Download the Product Manual</a>
                                <a href="/Support/?product=739" class="button primary expand help-button">
                                  <i class="fa fa-question-circle"></i>Need Help? Ask our experts</a>
                            </div>
                        </div>
                    </div>
```
NEW
```HTML
<div class="sidebar-product-manual-container">
                        
                        <div class="row">
                            <div class="columns">
                                <div class="warranty">2-year limited warranty
                                <a target="_blank" href="/getattachment/83119dfc-9adf-4955-bdb0-cd85eff876ed/attachment.aspx" class="button primary expand manual-button"><i class="fa fa-book"></i>Download the Product Manual</a>
                                <a href="/Support/?product=739" class="button primary expand help-button">
                                  <i class="fa fa-question-circle"></i>Need Help? Ask our experts</a>
                              </div>
                            </div>
                        </div>
                    </div>
```

**Comment by nickpaventi** [comment]
@MartyBeckers for - Find a Retailer CTA (and content below it) should be in-line horizontally with the top of the product name text

Looks like we need to leave .find-store-container .top-text-wrapper in the page even if it is empty, that will force the CTA to align with the product name.

**Comment by nickpaventi** [comment]
@MartyBeckers can you add a div right inside div class="product-detail-gallery" called div class="detail-gallery-overlay"? I've added the CSS for this and it should take care of - CHANGE FROM COMP Need to add a mask over the background image, screen shot of updated comp attached

```HTML
<div class="product-detail-gallery" style="background-image: url("/culligandiy/media/img/product-specialty-filters.jpg"); background-color: rgb(0, 0, 0);">
   <div class="detail-image-overlay"></div>
```

**Comment by nickpaventi** [comment]
@MartyBeckers this will be a site wide change for -  The wider/2-up product display is not consistent with the comps (image on left side, etc.)

Just need to add the class medium-6 to the 2 div class="small-12" inside inner-wrapper > row
OLD
```HTML
<div class="row featured-products">
		<div class="small-12 medium-6 columns end">
			<div class="outer-wrapper">
				<div class="inner-wrapper" style="min-height: 449px;">
					<div class="row">
						<div class="small-12 columns"><img src="/getmetafile/83e7c299-861a-4baa-b0d7-bd88606aab2f/PR-1_full.aspx?maxsidesize=168" alt=""></div>
						<div class="small-12 columns greater-than">
```
NEW
```HTML
<div class="row featured-products">
		<div class="small-12 medium-6 columns end">
			<div class="outer-wrapper">
				<div class="inner-wrapper" style="min-height: 449px; height: auto;">
					<div class="row">
						<div class="small-12 medium-6 columns"><img src="/getmetafile/83e7c299-861a-4baa-b0d7-bd88606aab2f/PR-1_full.aspx?maxsidesize=168" alt=""></div>
						<div class="small-12 medium-6 columns greater-than">
							
```

**Comment by MartyBeckers** [comment]
Hi @nickpaventi - this ticket is getting a little overwhelming and I'm not sure it makes sense for me to implement all of these changes since I'm not sure what they are trying to accomplish.  Do you want to give it a shot and let me know if you run into trouble?  All of the code listed here should be at http://dev.culligandiy.com/CMSSiteManager/ > Development > Page templates > Culligan DIY > Culligan DIY Product Detail.  Then you can first look for the HTML in the "Layout" tab, and if it's not there, there will be a zone placeholder.  Switch over to the "Design" tab and find that same zone placeholder, then press the sprocket next to an item within it.  You can scan through that form for HTML and press the "Source" button if you're looking at a text field, but it's usually in the "Edit" button next to "Transformation".  That all sounds complicated, but once you find the HTML, it's a simple matter to make changes and that will allow you to implement your own changes without hoping that I understood and implemented them correctly.  If you run into trouble, you can IM me on Skype at marty.beckers or call/text me at 661-644-1216 and I can either walk you through it or take on any pieces you're having trouble with.

**Comment by nickpaventi** [comment]
@MartyBeckers, thanks I was able to knock out most of these. There are 2 changes I still need help with:

First - this will fix the Related Products layout so if the wide format shows the display will be image on the left with text and links on the right (instead of staked how it is now)

This will be a site wide change for -  The wider/2-up product display is not consistent with the comps (image on left side, etc.)

NEED THIS LOGIC - if the div inside div class="row featured-products" DOES NOT have large-3
THEN need to add the class medium-6 to the 2 div class="small-12" inside inner-wrapper > row

OLD
```HTML
<div class="row featured-products">
		<div class="small-12 medium-6 columns end">
			<div class="outer-wrapper">
				<div class="inner-wrapper" style="min-height: 449px;">
					<div class="row">
						<div class="small-12 columns"><img src="/getmetafile/83e7c299-861a-4baa-b0d7-bd88606aab2f/PR-1_full.aspx?maxsidesize=168" alt=""></div>
						<div class="small-12 columns greater-than">
```
NEW
```HTML
<div class="row featured-products">
		<div class="small-12 medium-6 columns end">
			<div class="outer-wrapper">
				<div class="inner-wrapper" style="min-height: 449px; height: auto;">
					<div class="row">
						<div class="small-12 medium-6 columns"><img src="/getmetafile/83e7c299-861a-4baa-b0d7-bd88606aab2f/PR-1_full.aspx?maxsidesize=168" alt=""></div>
						<div class="small-12 medium-6 columns greater-than">
							
```

Second - for Find a Retailer CTA (and content below it) should be in-line horizontally with the top of the product name text

Looks like we need to leave div class="find-store-container" > div class="top-text-wrapper" on the page even if it is empty, that will force the CTA to align with the product name. I saw this in the code Detail Panel, but it was surrounded by some logic and I didn't want to break anything.

**Comment by MartyBeckers** [comment]
Ok great, these remaining changes are in place.

**Comment by nickpaventi** [comment]
@mikewestaz can you take another look at this page and make sure everything you pointed out has been taken care of?

**Comment by mikewestaz** [comment]
@MartyBeckers @zheindel @yuchentai @nickpaventi - Closing this monster ticket.
