### ISSUE TITLE
Footer: (From QA) New telephone link issues

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#112]
In both IE and Chrome, clicking the phone number in the footer causes an error to occur:
a.  In IE, clicking the phone number takes the user to a Page cannot be displayed error with tel://1-800-721-9243/ in the URL window.
b.  In Chrome, clicking the phone number just refreshes the page and does nothing.

**Comment by nickpaventi** [comment]
@MartyBeckers the // needs to be removed, should just be tel:1-800-721-9243, where can we edit this in the CMS?

**Comment by MartyBeckers** [comment]
Ok I just changed it (http://dev.culligandiy.com/CMSDesk/ > Culligan DIY > Page tab > wrench next to the phone number) but QA is still reporting the same results. Should we just remove the link and display it as text?

**Comment by nickpaventi** [comment]
@mikewestaz is this the desired functionality? For me it's click to call on mobile and on desktop the browser prompts you for an application that can make phone calls. I don't get redirected to a 404 page.

**Comment by mikewestaz** [comment]
@nickpaventi this appears to function correctly. Closing ticket.
