### ISSUE TITLE
Product Teasers: (From QA) Hover causes distortion

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#113]
In both IE and Chrome, hovering over the green product teaser boxes (such as the ones for the related products) causes the text word wrapping to shift.  Click the Replacements link, then scroll to the bottom and hover back and forth over the “Shower Head Filters & Parts” box: The thickness of the box border is causing the text to wrap differently when in a hovered and non-hovered state.

**Comment by nickpaventi** [comment]
Closing. Related to #63
