### ISSUE TITLE
Header Search Box: (From QA) Broken and missing watermark in IE

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#114]
The word, “Search” is missing from the search box:

![image](https://cloud.githubusercontent.com/assets/11283011/7091267/6afedaf2-df5d-11e4-9ef3-c07368d21f13.png)

and Search functionality is completely broken (typing text in the box does nothing)

**Comment by nickpaventi** [comment]
Removed top and bottom padding which was causing the text to disappear, add in some box-sizing and height:

```HTML
.top-header form input, .top-header-search-area input {
    border: none;
    padding-left: 40px;
    font-size: 15px;
    margin: 0;
    padding: 0 40px;
    border-radius: 5px;
    height:42px;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
  }
```
