### ISSUE TITLE
Category Landing [Mobile]: (From QA) Problem tags too wide

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#117]
http://dev.culligandiy.com/Undersink-Systems and Product pages: problem tag text is overlapping and going outside the frame of (or butting up against the frame of) the blue boxes:

![image](https://cloud.githubusercontent.com/assets/11283011/7091530/21e794c4-df5f-11e4-8171-433b06c6cc76.png)

**Comment by nickpaventi** [comment]
Added white-space at line 15066
