### ISSUE TITLE
Solution Guide [Mobile]: (From QA) White space between products

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#119]
http://dev.culligandiy.com/Solutions/?problem=15: There are varying degrees of white space between products listed on the Solutions page and related products sections of all pages:

![image](https://cloud.githubusercontent.com/assets/11283011/7091663/4643800c-df60-11e4-821c-7608f972a195.png)

![image](https://cloud.githubusercontent.com/assets/11283011/7091683/7976a79c-df60-11e4-8a09-be7d2c132edc.png)

**Comment by nickpaventi** [comment]
Fixed, removed margin at 13785
