### ISSUE TITLE
Category Landing [Mobile]: (From QA) Big headline too large

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#120]
http://dev.culligandiy.com/Replacements: The “ts” at the end of “Replacements” is getting cut off.  This is happening with all longer words in titles (like “Refrigerator” and “House/Sediment”) as well, and it pushes the entire text for the page to the left:

![image](https://cloud.githubusercontent.com/assets/11283011/7091730/efe8b320-df60-11e4-8404-4c28889236fb.png)

![image](https://cloud.githubusercontent.com/assets/11283011/7091754/2138e436-df61-11e4-888a-c8d90c286391.png)

**Comment by nickpaventi** [comment]
@mikewestaz this is an issue at 320px for some of these longer words and words combined using a / with no spaces. We already bumped down the font size, is this a content issue or should we shrink the font-size further?

**Comment by mikewestaz** [comment]
I think we need to work on the content itself-is there a page in particular I should look at?

**Comment by nickpaventi** [comment]
@mikewestaz you bet - http://dev.culligandiy.com/Whole-House-Systems

**Comment by mikewestaz** [comment]
Yes, the content needs to be edited. Something like 'Whole House & Sediment Filtration' solves this issue. 

cc @zheindel

**Comment by zheindel** [comment]
This is done
