### ISSUE TITLE
Home Page [Tablet]: (From QA) Button links cut off

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#124]
On an iPad Air in vertical orientation, the copy links are getting cut off:

![image](https://cloud.githubusercontent.com/assets/11283011/7095525/027d3e74-df80-11e4-8826-9991597fc2a8.png)

Note that if you rotate to horizontal and then back to vertical, the buttons are no longer cut off

**Comment by seanriceaz** [comment]
Fixed. added `overflow:hidden;` at 13810
