### ISSUE TITLE
Home Page [Tablet]: (From QA) Callout text overlapping and unreadable

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#125]
On an iPad Air in vertical orientation (but not horizontal), the callout text is overlapping and unreadable:

![image](https://cloud.githubusercontent.com/assets/11283011/7095582/7aff67d2-df80-11e4-9412-da0efa34999e.png)

**Comment by MartyBeckers** [comment]
![image](https://cloud.githubusercontent.com/assets/11283011/7095621/a78da1b0-df80-11e4-9fb7-1bcaead4b728.png)

**Comment by mikewestaz** [comment]
Already entered https://github.com/nickpaventi/culligan-diy/issues/89
Closing this version
