### ISSUE TITLE
Find a Retailer: 4 images under Lowe's should be 1 image

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#127]
Due to image availability, there is one image to use here.
Should be one image occupying the same space as all 4.

Image placement listing in the tracking sheet:
https://docs.google.com/a/ethology.com/spreadsheets/d/1PyCH6n2UvXViw7LaDdRNiD42N5iUPlEkyg9YY-PbeDI/edit#gid=1312084835

Photo attached
![lowes-feature-image](https://cloud.githubusercontent.com/assets/10550484/7097591/e7b89262-df8b-11e4-9448-42c42d8bad48.jpg)

**Comment by nickpaventi** [comment]
@MartyBeckers another one I think I need your help on. I tried to add this in zoneShopOnlineLink under Link1, but I don't see any editing privileges. The code should change to: 

OLD
```HTML
<div class="row collapse image-grid">
                <div class="columns small-12">
                    <img src="/culliganDIY/media/img/find-a-retailer/kitchen-faucet.png">
                    <img src="/culliganDIY/media/img/find-a-retailer/kitchen-faucet.png">
                </div>
                <div class="columns small-12">
                    <img src="/culliganDIY/media/img/find-a-retailer/kitchen-faucet.png">
                    <img src="/culliganDIY/media/img/find-a-retailer/kitchen-faucet.png">
                </div>
            </div>
```

NEW
```HTML
<div class="row collapse image-grid">
    <img src="/culliganDIY/media/img/find-a-retailer/NEW-FILENAME.jpg">
</div>
```

**Comment by nickpaventi** [comment]
Thanks! Updated the CSS and this is all set now.
