### ISSUE TITLE
Global Footer: Links for 'About' 'Terms' and 'Privacy' missing

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#133]
Can't tell if these pages are missing or if just the links are. @zheindel any information here?

**Comment by zheindel** [comment]
@mikewestaz think we just want these to link to the below:

About - http://www.culligan.com/en-us/d/what-we-do/
Terms- http://www.culligan.com/en-us/d/company/terms-and-conditions/
Privacy- http://www.culligan.com/en-us/d/company/privacy-policy/

**Comment by mikewestaz** [comment]
@MartyBeckers @nickpaventi @zheindel Thanks Zack, not sure who's the right person to apply that buy correct links are listed above...

**Comment by seanriceaz** [comment]
@MartyBeckers I went in and did some tweaks on this, including adding the link href's in. Assinging to you, since this is a backend issue now.

HOWEVER, the `href` attribute of the links isn't rendering to the browser. Not sure why.

**Comment by MartyBeckers** [comment]
Ok these are in place.  For future reference, the editable content elements in the header/footer can be changed in http://dev.culligandiy.com/CMSDesk/ > Culligan DIY > Page > wrench next to the link
