### ISSUE TITLE
Sitemap: Many links produce error page and links repeated

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#134]
@MartyBeckers Not sure if this is placeholder sitemap or generated dynamically
cc @zheindel 

http://dev.culligandiy.com/Sitemap

![screenshot 2015-04-10 14 45 49](https://cloud.githubusercontent.com/assets/10550484/7098023/5fbe1468-df90-11e4-924e-a8a77a0c4305.png)

**Comment by seanriceaz** [comment]
assigning this to @MartyBeckers Since it seems like a dev issue.

**Comment by MartyBeckers** [comment]
That was a temporary issue during development, please try again.
