### ISSUE TITLE
Solution Center: Modal needed for 'Hard Water' selection

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#135]
Per the email thread from @MartyBeckers - Proposed modal solution for Hard Water selection is on InVision http://invis.io/KE2OC0ETB and loaded here.

Should link to: http://www.culligan.com/en-us/d/appointment/schedule-an-appointment/
cc @nickpaventi @zheindel 

![solutions center modal](https://cloud.githubusercontent.com/assets/10550484/7098148/ee7e9802-df91-11e4-8378-6a1fc04e09c8.jpg)

**Comment by MartyBeckers** [comment]
This doesn't look too bad - will someone be able to provide me with HTML/CSS that I can integrate into Kentico?

**Comment by mikewestaz** [comment]
@nickpaventi or @seanriceaz - think we can knock this out static for @MartyBeckers ?

cc @zheindel

**Comment by nickpaventi** [comment]
@MartyBeckers please use the following HTML for this modal

```HTML
<div style="" class="callout-modal">
  <div class="callout-modal-wrapper">
    <div class="callout-content">
      <h2>Hard Water Issues?</h2>
      <p>Contact Your Local Culligan Man</p>
      <p>If hard water is a household problem, your local Culligan Man will be able to test your water and make recommendations for a water softner or water conditioning solution for your home or business.</p>
      <input type="submit" value="Find A Culligan Man" class="button primary">
    </div>
    <a class="close-callout-modal" href="#">Close</a>
  </div>
</div>
```

**Comment by MartyBeckers** [comment]
Ok this is in place and functional.
