### ISSUE TITLE
Product Detail [Tablet]: (From QA) Product Manual and Ask Expert wrapping

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#136]
Product Manual and Ask expert buttons are wrapping oddly on an iPad Air in vertical orientation:
![image](https://cloud.githubusercontent.com/assets/11283011/7099575/bc390ff8-dfaa-11e4-9461-f32603ffa45a.png)

**Comment by nickpaventi** [comment]
fixed
