### ISSUE TITLE
Solutions [Tablet]: (From QA) Find Solutions button cut off

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#137]
Text for the Find Solutions button is getting cut off on an iPad Air in vertical orientation:

![image](https://cloud.githubusercontent.com/assets/11283011/7099578/de8bff0c-dfaa-11e4-87a2-2f3b77bed658.png)

**Comment by yuchentai** [comment]
Fixed the padding issue that causes button being cut off on iPad 3/4, should be the same result on iPad Air.
