### ISSUE TITLE
Product Detail [Tablet]: (From QA) Feature text overlaps

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#139]
http://dev.culligandiy.com/Faucet-Filters/Chrome-Faucet-Mount-Water-Filter: Text overlaps images on an iPad Air in vertical orientation:

![image](https://cloud.githubusercontent.com/assets/11283011/7099613/ca8953dc-dfab-11e4-92b7-219e973230e8.png)

**Comment by mikewestaz** [comment]
Closing this. There is another to me that will resolve. 
Thanks!
