### ISSUE TITLE
Home Page: (From QA) New callout images don't line up

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#141]
The blue dot no longer lines up well with the new callout images at the bottom of the page and the second one is cut off:

![image](https://cloud.githubusercontent.com/assets/11283011/7103521/a744b9a2-e05f-11e4-9448-ce216e082258.png)

![image](https://cloud.githubusercontent.com/assets/11283011/7103523/c328f958-e05f-11e4-9154-da41790b7138.png)

**Comment by nickpaventi** [comment]
I fixed the cutoff issue.

@mikewestaz you want to get with me to knock out the positioning of this one first thing Monday AM? Should be an easy fix, just changing some positioning values.

**Comment by mikewestaz** [comment]
Sure @nickpaventi but before we worry about that we need the content so that we know what to highlight. The client has not provided anything for the homepage yet (please confirm @zheindel )

**Comment by zheindel** [comment]
@mikewestaz That is correct still waiting on that content from the client

**Comment by nickpaventi** [comment]
N/A
