### ISSUE TITLE
Category Landing [Tablet]: (From QA) Subcategory landing text problem

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#142]
[Discovered on an Android tablet but occurs in a browser as well]

When viewing pages that have sub-categories (so it doesn’t occur with Refrigerator Filters or Specialty Filters pages, but all others), you can see, “Choose a system”.  When you click that link, the word, “system” gets pushed to the far right, and it is overlapped by some minus symbols.  If you click on that link again (the close or minus symbols), then you see the ++ symbols overlapping the word “system”

![image](https://cloud.githubusercontent.com/assets/11283011/7103543/fa84fd4c-e060-11e4-8ed6-474d906b6775.png)

**Comment by nickpaventi** [comment]
Same issue as #104
