### ISSUE TITLE
IE Compatibility: (From QA) Internet Explorer 9 layout problems

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#144]
IE 10/11 are working great now, but IE 9 displays with problems.  Note that there are no IE 9 error messages and the layout problems don't occur in the IE 11 Emulator, only a real browser (http://www.browserstack.com is the easiest way to see the issue):

![image](https://cloud.githubusercontent.com/assets/11283011/7119021/ed1521ca-e1b7-11e4-80fc-baad624e9c67.png)

**Comment by seanriceaz** [comment]
Here are some linter results:
http://infohound.net/tidy/tidy.pl?_function=tidy&_url=http%3A%2F%2Fdev.culligandiy.com%2FShower-Head-Filters&_html=&alt-text=&doctype=auto&fix-backslash=y&fix-bad-comments=y&fix-uri=y&join-styles=y&lower-literals=y&ncr=y&new-blocklevel-tags=&new-empty-tags=&new-inline-tags=&new-pre-tags=&output-xhtml=y&quote-ampersand=y&quote-nbsp=y&indent=auto&indent-spaces=2&tab-size=4&wrap=90&wrap-asp=y&wrap-jste=y&wrap-php=y&wrap-sections=y&ascii-chars=y&char-encoding=ascii&input-encoding=latin1&output-bom=auto&output-encoding=ascii&_output=warn

Are you guys using html5 elements like `<section>`, `<nav>`, `<header>` etc? Looks like you're not, but if you are, you've got the wrong doctype.

Might be helpful just to change that doctype to
```html
<!DOCTYPE html>
```

Regardless.

**Comment by MartyBeckers** [comment]
Ok the new doctype is in place but it didn't change anything in IE 9.

**Comment by nickpaventi** [comment]
Looks like the CSS didn't load to me. I have a PC at home and will check this on my lunch

**Comment by nickpaventi** [comment]
@MartyBeckers the issue was that IE9 stops loading CSS rules after about 4000 in one file. We split the Culligan DIY css into 2 files and things seem to be working now. Please re-test

**Comment by MartyBeckers** [comment]
That fixed it right up!
