### ISSUE TITLE
Updating Tag "Aesthetic Chlorine Taste & Odor"

### ISSUE THREAD

**Issue by zheindel** [nickpaventi/culligan-diy#145]
@MartyBeckers - can you update it where it says "Aesthetic Chlorine Taste & Odor" for the old products so it just says "Chlorine" and that way all the products are consistent with that tag.

Thanks

**Comment by MartyBeckers** [comment]
Ok this change is in place.

**Comment by zheindel** [comment]
Thanks @MartyBeckers
