### ISSUE TITLE
Product Manual Library - Update with Model number

### ISSUE THREAD

**Issue by zheindel** [nickpaventi/culligan-diy#146]
One more quick observation. The product manual library needs some work. http://dev.culligandiy.com/Product-Manual-Library/
 
The subcategories are all there and that’s great. But we want the model number of each product under those subcategories to be displayed and not the description. Also, the “Replacements” subcategory should not be listed in the product manual library. Replacement filters are linking to the system that they are used in, which is redundant since they are already listed somewhere the previous sections.

**Comment by MartyBeckers** [comment]
Ok these changes are in place.
