### ISSUE TITLE
Verify that thumbnail photos and videos are in place and funtioning

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#149]
I am not able to find products with these on the site currently

**Comment by mikewestaz** [comment]
@MartyBeckers - I'm breaking up that large PDP ticket https://github.com/nickpaventi/culligan-diy/issues/107 so if these items I'm creating you have validated elsewhere please feel free to close this!

**Comment by MartyBeckers** [comment]
We created temporary placeholder thumbnails/video for demonstration on the product at http://dev.culligandiy.com/Shower-Head-Filters/Wall-Mount/RainDisc-Filtered-Showerhead, but none of the products from the original Ektron site had more than one photo and Culligan only provided more than one photo on occasion (http://dev.culligandiy.com/basic-direct-connect-filter is an example).  So I believe the answer to this is yes the website supports multiple photos and a video for each product, but Culligan isn't making use of that functionality at this time.

**Comment by mikewestaz** [comment]
Thanks @MartyBeckers - closing task!
