### ISSUE TITLE
Header Images with Floating Products

### ISSUE THREAD

**Issue by zheindel** [nickpaventi/culligan-diy#152]
Hi Team,

Culligan has decided for the header image that we will be using a background image and then a product image "highlighted" and "Floating" on top.  This means it will be two separate images and we will need some front-end and backend dev so when this resizes the image doesn't get cut off and stays in the center on mobile.  

@mikewestaz will be mocking these up and providing the images 
@MartyBeckers - will need to apply front end dev changes.

I will be scheduling a call for us tomorrow to quickly get on the phone to discuss, but this should be the last big code change we need to make.

**Comment by nickpaventi** [comment]
added
