### ISSUE TITLE
New Home Page: (From QA) Revised layout doesn't match mockup

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#154]
Now that the new content is in place, there are some front-end styles that don't match the mockups.

1. The new product photo should overlap the new gray bar:
![image](https://cloud.githubusercontent.com/assets/11283011/7462626/e0264ed8-f267-11e4-967c-6b72b792ca99.png)

2. The gap is too large below the intro paragraph in both desktop and mobile:
![image](https://cloud.githubusercontent.com/assets/11283011/7462648/0e8b70aa-f268-11e4-979c-f81c44fa0bfa.png)

3. The gap is too large above the first product:
![image](https://cloud.githubusercontent.com/assets/11283011/7462680/51000e5a-f268-11e4-8155-ed2cab0b8c8c.png)

4. In the section at the bottom, the paragraph is indented beyond the title:
![image](https://cloud.githubusercontent.com/assets/11283011/7463913/95fa6e56-f272-11e4-85b3-66d2e1b78a87.png)

5. The blue section at the bottom is taller and darker in the mockup:
![image](https://cloud.githubusercontent.com/assets/11283011/7463940/cefaefc8-f272-11e4-8ec1-e533862c57e4.png)
![image](https://cloud.githubusercontent.com/assets/11283011/7463949/e7068a96-f272-11e4-9cb7-298d682fea88.png)

6. The gap above the third and sixth photo is too large in the mobile version:
![image](https://cloud.githubusercontent.com/assets/11283011/7464005/86c3cbca-f273-11e4-8222-a575fd94778c.png)

**Comment by nickpaventi** [comment]
fixed 2,3,4 and 6

**Comment by nickpaventi** [comment]
@mikewestaz for part 5 here, I see that the correct color is #006699, but when I convert that to RGB and give it an opacity (ex: rgba(0, 102, 153, .8)) it does not match the comp. Can you send the RGB value with opacity to me to implement?

**Comment by nickpaventi** [comment]
fixed part 1

**Comment by mikewestaz** [comment]
@nickpaventi - the hex is right, blending mode just needs to be set to multiply (it's not an opacity) so the water image shows through it. 

cc @zheindel

**Comment by nickpaventi** [comment]
@zheindel should be all set here
