### ISSUE TITLE
Missing mobile content

### ISSUE THREAD

**Issue by nickpaventi** [nickpaventi/culligan-diy#156]
@MartyBeckers the home page hero is missing content on mobile, please add the same content from the home page to this div:

![screen shot 2015-05-05 at 12 08 11 pm](https://cloud.githubusercontent.com/assets/10563172/7480773/d6fb7578-f31f-11e4-9704-a4d806b77a39.png)

**Comment by MartyBeckers** [comment]
@nickpaventi can you clarify this?  I'm seeing the home page and category landing page header content on mobile:
![image](https://cloud.githubusercontent.com/assets/11283011/7484875/f35550b8-f342-11e4-92c1-0fc3d771f375.png)
![image](https://cloud.githubusercontent.com/assets/11283011/7484880/0e1f8f6c-f343-11e4-9d33-097ebb24ac5e.png)

If that's not what you're referring to, can you send a screenshot showing what's missing?

**Comment by nickpaventi** [comment]
@MartyBeckers sorry, I just realized that if I switch out of "preview mode" this works as expected
