### ISSUE TITLE
Spacing with Water

### ISSUE THREAD

**Issue by zheindel** [nickpaventi/culligan-diy#157]
Hi Nick - small issue with spacing just need to move the water image up some see screenshot attached

First sticky
Tighten up this area. There is too much blank space between the end of the paragraph and the water graphic.

Second Sticky
Correct spacing. The word Ultrafiltration should appear below the water graphic and not over it. Move the image of the product at the same time so that there is a little bit of spacing between the two.
![screen shot 2015-05-06 at 11 07 02 am](https://cloud.githubusercontent.com/assets/11874973/7500028/0da539f4-f3e0-11e4-8cd1-65dceb6e4d40.png)

**Comment by nickpaventi** [comment]
@zheindel what browser is this in?

**Comment by zheindel** [comment]
Good question I'll ask as I can't reproduce on our side.

Z

**Comment by zheindel** [comment]
Any idea on this, clients comment is below with screenshot?  Is it cookies?  Or possibly something else?

@nickpaventi 
I’m using Chrome as a browser and this is how it looks to me:
![unnamed 1](https://cloud.githubusercontent.com/assets/11874973/7502713/e667bf66-f3f2-11e4-8ba9-b06caeb241b8.png)

**Comment by zheindel** [comment]
@nickpaventi had him clear his cache, we goo!
