### ISSUE TITLE
Homepage mobile product w/Dots

### ISSUE THREAD

**Issue by nickpaventi** [nickpaventi/culligan-diy#22]
Formatting needs to adjust on mobile, still show product and image side by side
![screen shot 2015-03-18 at 12 21 07 pm](https://cloud.githubusercontent.com/assets/10563172/6717424/8a5d1d38-cd69-11e4-8a37-0ef9fcbd47f1.png)

**Comment by thompsizzle** [comment]
Hey Nick,

This mobile design shows it stacked,

https://projects.invisionapp.com/d/main#/console/2979124/68432269/preview

Thanks!

**Comment by nickpaventi** [comment]
You are right, I had an old comp
