### ISSUE TITLE
Global Footer mobile

### ISSUE THREAD

**Issue by nickpaventi** [nickpaventi/culligan-diy#24]
Font size issues, spacing, social icons too big
![screen shot 2015-03-18 at 12 21 54 pm](https://cloud.githubusercontent.com/assets/10563172/6717456/c0ae6df6-cd69-11e4-80f8-edd755be547e.png)
![screen shot 2015-03-18 at 12 22 09 pm](https://cloud.githubusercontent.com/assets/10563172/6717457/c0c683a0-cd69-11e4-8fa9-974f55c2e4bd.png)

**Comment by thompsizzle** [comment]
Looks like I zoomed into the design too much.

**Comment by nickpaventi** [comment]
@thompsizzle - Looks better, still too much space between the links directly under Customer Support. Too much space under and above the social icons

**Comment by thompsizzle** [comment]
Okay. Should look better now!
