### ISSUE TITLE
Global [Desktop + Tablet]: Top and product navigation needs adjustment for smaller screens

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#51]
Need to adjust padding or styles to allow for the smaller screens to not have the buttons stack/wrap as they do now (applies to tablet as well). Maybe breakpoint for tablet to receive the mobile nav should be lower? 768 or 800?

![screenshot 2015-03-23 20 49 39](https://cloud.githubusercontent.com/assets/10550484/6795515/259b179a-d19e-11e4-95fd-706b8628cf85.png)

![screenshot 2015-03-23 20 46 20](https://cloud.githubusercontent.com/assets/10550484/6795494/c141adae-d19d-11e4-83d6-4fd0e69dbd1d.png)

![screenshot 2015-03-23 20 48 06](https://cloud.githubusercontent.com/assets/10550484/6795500/f5f4b0a0-d19d-11e4-9a36-41562403516e.png)

**Comment by nickpaventi** [comment]
This is resolved, we show the mobile nav at 1023px and under
