### ISSUE TITLE
Green product teaser box styling

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#63]
The green teaser boxes like the ones at http://culligandiy.dev.ethology.com/category-landing/, http://dev.culligandiy.com/Undersink-Systems, and http://dev.culligandiy.com/Undersink-Systems/Ultra-Filtration-Systems/3-Stage-Ultrafiltration-Drinking-Water-System look good when there are four with the same height, but when there are two or three they get spread out with a gap in between and the varying heights look odd

**Comment by mikewestaz** [comment]
To elaborate on @MartyBeckers original ticket...
- [ ] If the products are 3-up they should center, leaving the gap on the left and right sides of the group, not between the products (or left justified as a fallback)
- [ ] If the products are 1 or 2-up (as seen under 'wall mount' here: http://dev.culligandiy.com/Shower-Head-Filters) then the alternate, 2-up horizontal product layout should be used (see second subcategory comp here: http://invis.io/YX2EPX7NE)

To account for the varying heights, we should use JS to equalize each row. There are however several content issues (length, tags, etc) that need resolution as well. I'll take this offline and solve with the client and post direction back here.

- [ ] Use JS to equalize each row height

**Comment by nickpaventi** [comment]
@MartyBeckers for part 1 of this I'm going to need some help from you. Can you add a counter and some logic that says:

if number of products = 3 then add the class "large-offset-2" to the first div class="small-12 medium-6 large-3 columns" inside div class="row featured-products". 

Add the class "end" to the last div class="small-12 medium-6 large-3 columns" inside div class="row featured-products".

**Comment by nickpaventi** [comment]
@MartyBeckers part 2 I will also need some logic added, but it's much simpler.

if number of products < 3 then remove the class "large-3" from div class="small-12 medium-6 large-3 columns" inside div class="row featured-products".

**Comment by MartyBeckers** [comment]
You bet, I'm happy to implement changes like this once the classes are in place.  I'm a little fuzzy on the logic though so please confirm this is all correct:
1 column total, column 1: add "end", remove "large-3"
2 columns total, column 1: remove "large-3"
2 columns total, column 2: add "end", remove "large-3"
3 columns total, column 1: add "large-offset-2"
3 columns total, column 2: no change
3 columns total, column 3: add "end"
4 columns total, columns 1-4: no change

**Comment by mikewestaz** [comment]
@MartyBeckers and @nickpaventi 
Following up on my note above re. handling the product display with this larger than anticipated volume of content, attached is something Nick has already implemented from a design POV so attaching for reference. 

Making the product display wider and adjusting the tag display a little. Will create other tickets as needed after these get implemented to finesse. 

![screen shot 2015-04-09 at 10 18 56 am](https://cloud.githubusercontent.com/assets/10550484/7072692/267e7f82-dea3-11e4-8d8a-b413cbdfa76e.png)

**Comment by nickpaventi** [comment]
@MartyBeckers you had it right, but per @mikewestaz comment above we are going to max out at 2 cols (not 4). So the following should be all you need to do:

remove "large-3" from all columns
1 column total, column 1: add "end"

**Comment by nickpaventi** [comment]
@mikewestaz @MartyBeckers sorry for the back and forth here, this is the final direction:

1 column total, column 1: add "end", remove "large-3"
2 columns total, column 1: remove "large-3"
2 columns total, column 2: add "end", remove "large-3"
3 columns total, column 1: add "large-offset-2"
3 columns total, column 2: no change
3 columns total, column 3: add "end"
4 columns total, columns 1-4: no change

Disregard my previous comment

**Comment by nickpaventi** [comment]
@MartyBeckers can you add the following JS to the featured-products div to set equal heights:

```javascript
<script type="text/javascript">
$(document).ready(function(){
    $('.featured-products').each(function(){
    	var highestBox = 0;
    	$('.outer-wrapper', this).each(function(){
    		if($(this).height() > highestBox) {
    			console.log(this);
    			highestBox = $(this).height();
    		}
    	});
    	$('.inner-wrapper',this).height(highestBox);
    });
});
</script>
```

**Comment by MartyBeckers** [comment]
Ok these changes are all in place, although it looks like the jQuery may need some refinements.  If you want to test your changes on the site, it's at http://dev.culligandiy.com/CMSSiteManager/ > Development > Page templates > Culligan DIY > Culligan DIY Master > Header.

**Comment by nickpaventi** [comment]
Yes the jQuery needs a little work and after 2 hours tweaking it I will revisit in the AM...

**Comment by nickpaventi** [comment]
jQuery is fixed. 

@MartyBeckers looks like we are down to just 2 columns on the home page, should be four:

1 column total, column 1: add "end", remove "large-3"
2 columns total, column 1: remove "large-3"
2 columns total, column 2: add "end", remove "large-3"
3 columns total, column 1: add "large-offset-2"
3 columns total, column 2: no change
3 columns total, column 3: add "end"
4 columns total, columns 1-4: no change

**Comment by nickpaventi** [comment]
@MartyBeckers Note on the above comment: this appears to be working fine on the category pages- http://dev.culligandiy.com/Undersink-Systems

But is not on the homepage.

**Comment by MartyBeckers** [comment]
Yes the same style code is shared by the home page, it's just that only two products were flagged as "Featured on the home page".  I've added two more products, although Culligan will likely want to select four products that they actually want to feature.

**Comment by nickpaventi** [comment]
@MartyBeckers thanks that makes sense!

One final change on this one, centering things didn't go so well on tablet sized devices. So to fix that we are going to left align all views.

Can you remove the logic that adds "large-offset-2" to the: 3 columns total, column 1

**Comment by nickpaventi** [comment]
@MartyBeckers one other thing I noticed here...

We have incorrectly nested divs here

```HTML

<div class="row featured-products">
    <div class="four-container"> 
        <div class="row featured-products">
```

Can you remove the outer <div class="row featured-products"> That will solve our horizontally scrolling screen on tablet.

**Comment by MartyBeckers** [comment]
Ok those changes are in place but it looks like they broke the display of the products at the bottom of the Category Landing page (http://dev.culligandiy.com/Undersink-Systems) and the Product Detail page (http://dev.culligandiy.com/Undersink-Systems/Direct-Connect-Systems/Basic-Under-Sink-Filter-System)

**Comment by nickpaventi** [comment]
@MartyBeckers Sure did! The fix here is to uncomment that div directly inside div class="four-container". We still need the div class="row featured-products" that is inside that div, just didn't need the one outside it. Thanks!

**Comment by MartyBeckers** [comment]
Ok I uncommented the div that I had commented earlier, but I'm having a hard time following what needs to be done for this ticket.  Here's the code:

<div class=""four-container"">
	<div class=""row featured-products"">
		[productHTML]
	</div>
</div>

Can you make the changes that are needed and paste the new code here?

**Comment by nickpaventi** [comment]
@MartyBeckers I think this is all set now. Before we had

```HTML
<div class="row featured-products">
    <div class="four-container"> 
        <div class="row featured-products">
```

Now we only have
```HTML
    <div class="four-container"> 
        <div class="row featured-products">
```

Notice that the extra div class="row featured products" is not wrapping div class="four-container" anymore

**Comment by MartyBeckers** [comment]
Well now it's just back to the way it was where this outputs to the home page:

```
    <div class="row featured-products">
        <div class="four-container">
            <div class="row featured-products">
```
and this outputs to the Category Landing pages and the Product Detail pages:
```
    <div class="four-container">
        <div class="row featured-products">
```
So will that work, or do you want the outer "row featured-products" div removed from the home page?

**Comment by nickpaventi** [comment]
@MartyBeckers Please remove the extra outer "row featured-products" for the home page, then we can close this out. thanks!

**Comment by MartyBeckers** [comment]
Ok that change is in place.

**Comment by nickpaventi** [comment]
Thanks!
