### ISSUE TITLE
IE font error

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#64]
A JavaScript error that reads “@font-face failed OpenType embedding permission check. Permission must be Installable.” prevents the correct font from displaying in the header with Internet Explorer

**Comment by nickpaventi** [comment]
@MartyBeckers can you retest this?

**Comment by MartyBeckers** [comment]
Still happening :/

**Comment by nickpaventi** [comment]
@MartyBeckers one more time, I think this is fixed.

**Comment by MartyBeckers** [comment]
It's fixed!
