### ISSUE TITLE
Video keeps playing after being closed

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#67]
The product at http://dev.culligandiy.com/Shower-Head-Filters/Wall-Mount/RainDisc-Filtered-Showerhead has been configured with placeholder photos/videos for testing and clicking the video and closing it results in the video continuing to play in the background

**Comment by nickpaventi** [comment]
@MartyBeckers I can reproduce this, is it browser specific?

**Comment by MartyBeckers** [comment]
It looks like it's working properly in Firefox, but not in IE or Chrome.  To reproduce, click on the thumbnails to slide to the video thumbnail, click on the video thumbnail to open the video panel, press play and wait for the voice to start, then press close and you can still hear the audio.

**Comment by nickpaventi** [comment]
@MartyBeckers I added some code to the page header in Page Templates > Culligan DIY > Culligan DIY Product Detail but I don't see my code on the page. Is there something I need to do to push this live?

**Comment by MartyBeckers** [comment]
That's strange, I haven't seen that before and changes to the header have always instantly appeared.  I wasn't able to get your header changes to save at all, so I moved them to the layout tab within the jQuery that was already at the bottom of the page.  That seemed to do it, but please let me know if you run into that issue again.  I also confirmed that your changes resolved the issue.
