### ISSUE TITLE
Contact Pages: Contact your Culligan Man link incorrect

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#68]
The contact/product support pages (http://dev.culligandiy.com/Contact-Us and http://dev.culligandiy.com/Support) have a panel in the bottom-right for contacting Culligan, but that would just go to the same page – should it be hidden on one or the other?

**Comment by nickpaventi** [comment]
@mikewestaz any insight on this?

**Comment by mikewestaz** [comment]
@MartyBeckers @nickpaventi This should link to http://www.culligan.com/en-us/d/appointment/schedule-an-appointment/

**Comment by nickpaventi** [comment]
fixed
