### ISSUE TITLE
Selected page in mobile header don't highlight

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#69]
The mobile header “Solution Guide” and “Find a Retailer” buttons don’t stay highlighted on those pages in the same way the desktop header buttons do

**Comment by nickpaventi** [comment]
@MartyBeckers can you change the class for these buttons when you are on each page from dark-button to dark-button-active? That will close this out

**Comment by MartyBeckers** [comment]
That's already how the links work in the desktop header, but the mobile header doesn't use the "dark-button" class (its only class is mobile-social).  I can apply "dark-button-active" to it, but that would make it a dark gray like this:

![image](https://cloud.githubusercontent.com/assets/11283011/7077425/8578e352-dec5-11e4-827a-8ae4d0fe9efb.png)

Instead of the normal blue like this:

![image](https://cloud.githubusercontent.com/assets/11283011/7077440/9f79b38a-dec5-11e4-9e04-f6b3ece3b289.png)

Is that ok, or is there another class we can apply to make them appear blue?

**Comment by mikewestaz** [comment]
@MartyBeckers I think the grey is fine.

**Comment by MartyBeckers** [comment]
Ok that's in place.
