### ISSUE TITLE
Update all marketing photography

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#70]
Tracking sheet for images is located here:
https://docs.google.com/a/ethology.com/spreadsheets/d/1PyCH6n2UvXViw7LaDdRNiD42N5iUPlEkyg9YY-PbeDI/edit#gid=1312084835

Optimized assets located here:
https://drive.google.com/a/tallwave.com/folderview?id=0BzVs2iiEx4OMREctLVREQ01xU2s&usp=sharing

See @mikewestaz with questions

**Comment by nickpaventi** [comment]
@MartyBeckers where is the media directory that can we upload new versions of these images?

**Comment by MartyBeckers** [comment]
http://dev.culligandiy.com/cmsdesk/ > Tools > Media

**Comment by nickpaventi** [comment]
@zheindel almost all of these images are in content, can you pass this info along to whoever is updating the hero images and such?

**Comment by nickpaventi** [comment]
@MartyBeckers can you change the following image formats, I can't find them in the code:

OLD
```HTML
<img class="full-width-droplet" src="/culliganDIY/media/img/innovative-droplet-full/droplet-full.png">
```
NEW
```HTML
<img class="full-width-droplet" src="/culliganDIY/media/img/innovative-droplet-full/droplet-full.jpg">
```

**Comment by MartyBeckers** [comment]
Yes the changes are in place.

**Comment by nickpaventi** [comment]
@zheindel I think all the images that are in code have been updated. Can you make sure the images in content entry are as well? At this point I think this ticket is the sam as #74

**Comment by MartyBeckers** [comment]
The remaining content images are in place as well now.
