### ISSUE TITLE
Global Navigation [DESKTOP]: Needs style updates

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#71]
- [x] Font is incorrect. DEV shows Open Sans should be DIN Medium.
- [x] When hovering the text changes position (shifts right). It should not. 
- [x] When clicking in the search field, the background should not turn white, just the text should be white.
- [x] Horizontal positioning of the top bar is all over the place, all text should follow the same baseline (see screen shot attached vs comp: http://invis.io/3F2F4N1KD)
- [x] Solutions Guide and Find a Retailer should have the same smooth-fade hover effect as the product category navigation.

![diy-global-header-horiz-alignment](https://cloud.githubusercontent.com/assets/10550484/7058776/215604fe-de1b-11e4-9694-84465f87ee04.png)

**Comment by nickpaventi** [comment]
@mikewestaz I don't see the hover position changing

**Comment by mikewestaz** [comment]
It's gone now @nickpaventi if you want to close ticket. I'll reopen if it comes back.
