### ISSUE TITLE
Global Navigation [TABLET]: Needs style updates

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#72]
**Horizontal 1024**
- [x] There are positioning issues to resolve within the top-navigation bar in 1024 viewport (see screen shot).
- [x] If we need to drop the 'Do it yourself' text under the logo that is fine, just add some padding between the logo and the text. 
- [x] Need 'Solutions' and 'Retailer' links to flow horizontally. 
- [x] I am able to scroll right and see a white gap on the right edge of the page (see screen shot, same at 768 viewport as well)

**Vertical 768**
- [x] Animation for slide out and close navigation should be faster, easing out at the end
- [x] With the navigation open, I can scroll right taking me back to the content and sliding the navigation around
- [x] Search field should not turn white when clicked into
- [x] There should not be a rule under 'Replacements', creates a double line (see screen shot)
- [x] The darker background color should continue all the way down the left side (see screen shot)
- [x] Ideally you could not scroll past the last navigation item into a big open space
- [x] 'Do it yourself' text next to the logo in the mobile menu should be larger. Recommend ``font-size: 20px;`` on mobile view

![screenshot 2015-04-08 18 26 19](https://cloud.githubusercontent.com/assets/10550484/7058880/c36c928e-de1c-11e4-9094-18d2d3f93e84.png)

![tablet-scroll-left](https://cloud.githubusercontent.com/assets/10550484/7058928/493e7512-de1d-11e4-993e-529e796edcb2.png)

![diy-tablet-nav](https://cloud.githubusercontent.com/assets/10550484/7059009/9e03691c-de1e-11e4-9a0d-b9b2f9a803a6.png)

![tablet-nav-background](https://cloud.githubusercontent.com/assets/10550484/7059031/fa32b936-de1e-11e4-81d1-61c5e0adcb95.png)

**Comment by nickpaventi** [comment]
@MartyBeckers for the issue in 768 (There should not be a rule under 'Replacements', creates a double line) would it be possible to add the class "no-border" to the Replacements anchor tag? The logic would ideally add this tag to the last li before the first li with class="mobile-social", not just target Replacements.

**Comment by MartyBeckers** [comment]
Yes that change is in place, although I should note that the site currently only allows for a fixed number of main categories (7) since there are so many areas of the code that would need to be changed by a developer in order to add/remove main categories.  So for now this class is just on the seventh category, although I'll be sure to note it so that if we go back and revise the site to accept an unlimited number of categories, the no-border class will go on the last one.

**Comment by nickpaventi** [comment]
Looks good, thanks!

**Comment by nickpaventi** [comment]
@MartyBeckers would it be possible to place a div immediately inside the body tag as an entire page wrapper for every page? We could give it div class="page-wrapper". Doing so would make resolving the off-screen nav issues 100 time easier.

**Comment by MartyBeckers** [comment]
Yes I've added it to the master template, although it's not quite the first div inside the body tag because of all of the stuff that Kentico adds automatically.  If that won't work, let me know and I can edit the core Kentico code to get it just inside the body tag.
