### ISSUE TITLE
Update product photography

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#74]
All product photography in the product listings and on the product detail pages should be the transparent PNG files Connie delivered.

**Comment by nickpaventi** [comment]
@zheindel this should be able to be done by the client or someone with content entry permissions

**Comment by zheindel** [comment]
@nickpaventi can you assign @MartyBeckers to this...his team will be updating the images.

Z

**Comment by MartyBeckers** [comment]
This is complete.
