### ISSUE TITLE
Global Product Listings: Need style updates

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#75]
- [x] Product name needs more line height. Recommend ``line-height: 1.3;``
- [x] Should be able to click anywhere (except the tags) and go to the product detail page. Currently, you have to click the words 'View details'
- [x] Product description text should be Open Sans, currently DIN
- [x] Hover should have same smooth fade transition as other buttons and navigation elements
- [x] 'View Details' should always be at the bottom of the block

Comp of homepage with sample product listing: http://invis.io/3F2F4N1KD 

![screenshot 2015-04-08 19 23 48](https://cloud.githubusercontent.com/assets/10550484/7059375/cd909366-de24-11e4-8f54-4a6a2acda673.png)

**Comment by mikewestaz** [comment]
Pulled from new ticket since this appears to be related:
Text updates and hover effects were added and look good, however text shifting bug was introduced.

See screen recording:
https://www.dropbox.com/s/zr4ol28irc1rmar/hover-issues.mov?dl=0

**Comment by nickpaventi** [comment]
@MartyBeckers can you move div class="view-details" outside of div class="small-12 columns greater-than" so that it is just next to div class="row"

OLD
```HTML
<div class="outer-wrapper">
				<div class="inner-wrapper" style="min-height: 880px;">
					<div class="row">
						<div class="small-12 columns"><img src="/getmetafile/0a9fc2f6-16b0-4c73-be30-d503770e312c/RDSH-C115_full.aspx?maxsidesize=168" alt=""></div>
						<div class="small-12 columns greater-than">
							<div class="featured-title">RainDisc&reg; Filtered Showerhead</div>
							<div class="featured-description hide-for-small">The Culligan RainDisc&reg; Chrome Filtered Showerhead will reduce sulfur odor, chlorine and scale for softer, cleaner skin and hair. The filter is easy to install with no tools required, and each filter cartridge lasts 10,000 gallons, or 6 months.&nbsp;</div>
							<div class="product-problem-links">
								<label>The Perfect Solution for</label>
								<input type="button" onclick="location.href='/Solutions?problem=14'" value="Chlorine" class="tablet button"><input type="button" onclick="location.href='/Solutions?problem=15'" value="Scale" class="tablet button"><input type="button" onclick="location.href='/Solutions?problem=16'" value="Sulfur Odor" class="tablet button">
							</div>
							<div class="view-details"><a href="/Shower-Head-Filters/Wall-Mount/RainDisc-Filtered-Showerhead">View details</a></div><!--795-->
						</div>
					</div>
				</div>
				<div class="featured-bar"></div>
			</div>
```

NEW
```HTML
<div class="outer-wrapper">
				<div style="min-height: 880px;" class="inner-wrapper">
					<div class="row">
						<div class="small-12 columns"><img alt="" src="/getmetafile/0a9fc2f6-16b0-4c73-be30-d503770e312c/RDSH-C115_full.aspx?maxsidesize=168"></div>
						<div class="small-12 columns greater-than">
							<div class="featured-title">RainDisc&reg; Filtered Showerhead</div>
							<div class="featured-description hide-for-small">The Culligan RainDisc&reg; Chrome Filtered Showerhead will reduce sulfur odor, chlorine and scale for softer, cleaner skin and hair. The filter is easy to install with no tools required, and each filter cartridge lasts 10,000 gallons, or 6 months.&nbsp;</div>
							<div class="product-problem-links">
								<label>The Perfect Solution for</label>
								<input type="button" class="tablet button" value="Chlorine" onclick="location.href='/Solutions?problem=14'"><input type="button" class="tablet button" value="Scale" onclick="location.href='/Solutions?problem=15'"><input type="button" class="tablet button" value="Sulfur Odor" onclick="location.href='/Solutions?problem=16'">
							</div>
							<!--795-->
						</div>
					</div>
  				<div class="view-details"><a href="/Shower-Head-Filters/Wall-Mount/RainDisc-Filtered-Showerhead">View details</a></div>
				</div>
				<div class="featured-bar"></div>
			</div>
```

**Comment by MartyBeckers** [comment]
Ok that change is in place.

**Comment by nickpaventi** [comment]
@mikewestaz even wrapping the entive div in a link will not let the user click anywhere and go to the product page (the big white space under the form buttons isn't clickable). Should we just link the image title and description, or do you want me to rig up some jquery?

**Comment by yuchentai** [comment]
@MartyBeckers can you please change this featured product? thanks
OLD
<div class="inner-wrapper">
		<div class="row">
			<div class="small-12 columns">
				<img src="../img/four-featured-products/feature-image-1.png" />
			</div>
			<div class="small-12 columns greater-than">
				<div class="featured-title">Product Name</div>
				<div class="featured-description hide-for-small">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>

New
<div class="inner-wrapper">
		<div class="row">
			<div class="small-12 columns">
                            <a href="#">
				<img src="../img/four-featured-products/feature-image-1.png" />
			
</div>
			<div class="small-12 columns greater-than">
				<div class="featured-title">Product Name</div>
				<div class="featured-description hide-for-small">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>

CSS
.featured-products .outer-wrapper .inner-wrapper a.featured-link {
  color: #554741;
  display: inline-block;
}
.featured-products .outer-wrapper .inner-wrapper a.featured-link .featured-title {
  font-size: 22px;
  font-weight: 800px;
  margin-top: 28px;
  font-weight: 100;
  line-height: 1.3em;
}
.featured-products .outer-wrapper .inner-wrapper a.featured-link .featured-description {
  margin: 12px 0 20px;
  line-height: 20px;
}
.featured-products .outer-wrapper .inner-wrapper a.featured-link:hover {
  color: #554741;
}

**Comment by yuchentai** [comment]
@MartyBeckers sorry the img tag above div.featured-title needs to be wrapped with a tag too.

**Comment by MartyBeckers** [comment]
@yuchentai can you provide the old/new code here with the extra tag you mentioned so that I can make sure I implement it correctly?

**Comment by nickpaventi** [comment]
@MartyBeckers all we need is to wrap the image, title and description in a tags...please note that the actual href would come from the div class="view-details" link

OLD
```HTML
<div class="outer-wrapper">
				<div class="inner-wrapper" style="min-height: 931px;">
					<div class="row">
						<div class="small-12 columns"><img src="/getmetafile/a1872345-d4c7-4515-9e8c-e546f001b584/US-EZ-3_full.aspx?maxsidesize=168" alt=""></div>
						<div class="small-12 columns greater-than">
							<div class="featured-title">Advanced Under Sink Filter System, Easy-Change</div>
							<div class="featured-description hide-for-small">The Culligan US-EZ-3 ADVANCED drinking water system provides 500 gallons of refreshing drinking water, and includes a stylish chrome drinking water faucet.</div>
							
```
NEW
```HTML
<div class="outer-wrapper">
				<div class="inner-wrapper" style="min-height: 931px;">
					<div class="row">
						<div class="small-12 columns"><a href="/Undersink-Systems/Direct-Connect-Systems/Advanced-Under-Sink-Filter-System,-Easy-Change"><img src="/getmetafile/a1872345-d4c7-4515-9e8c-e546f001b584/US-EZ-3_full.aspx?maxsidesize=168" alt=""></a></div>
						<div class="small-12 columns greater-than">
							<div class="featured-title"><a href="/Undersink-Systems/Direct-Connect-Systems/Advanced-Under-Sink-Filter-System,-Easy-Change">Advanced Under Sink Filter System, Easy-Change</a></div>
							<div class="featured-description hide-for-small"><a href="/Undersink-Systems/Direct-Connect-Systems/Advanced-Under-Sink-Filter-System,-Easy-Change">The Culligan US-EZ-3 ADVANCED drinking water system provides 500 gallons of refreshing drinking water, and includes a stylish chrome drinking water faucet.</a></div>
```

**Comment by MartyBeckers** [comment]
Ok those changes are in place.

**Comment by nickpaventi** [comment]
@MartyBeckers please note I just updated the code a little, can you double check the changes you just made?

**Comment by MartyBeckers** [comment]
Yes I had put the first round of code in place, then when I was going to write "done" I noticed it had changed and put the new changes in place :)

**Comment by nickpaventi** [comment]
Thanks! Can you add class="featured-link" to the new a tags?

This is the HTML I am seeing
```HTML
<div class="small-12 columns greater-than">
							<div class="featured-title"><a href="/Undersink-Systems/Direct-Connect-Systems/Advanced-Under-Sink-Filter-System,-Easy-Change">Advanced Under Sink Filter System, Easy-Change</a></div>
							<div class="featured-description hide-for-small"><a href="/Undersink-Systems/Direct-Connect-Systems/Advanced-Under-Sink-Filter-System,-Easy-Change">The Culligan US-EZ-3 ADVANCED drinking water system provides 500 gallons of refreshing drinking water, and includes a stylish chrome drinking water faucet.</a></div>
```
Should be
```HTML
<div class="small-12 columns greater-than">
							<a class="featured-link" href="/Undersink-Systems/Direct-Connect-Systems/Advanced-Under-Sink-Filter-System,-Easy-Change"><div class="featured-title">Advanced Under Sink Filter System, Easy-Change</div>
							<div class="featured-description hide-for-small">The Culligan US-EZ-3 ADVANCED drinking water system provides 500 gallons of refreshing drinking water, and includes a stylish chrome drinking water faucet.</div></a>
```

**Comment by MartyBeckers** [comment]
Ok that's in place.

**Comment by nickpaventi** [comment]
Thank you!
