### ISSUE TITLE
Home [Desktop & Tablet]: CTAs in product feature do not function

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#78]
When clicking the feature product CTAs no product search is returned

![home-feature-ctas](https://cloud.githubusercontent.com/assets/10550484/7073182/79e5ee6e-dea6-11e4-9d25-2e7c00a76133.png)

**Comment by nickpaventi** [comment]
@MartyBeckers can you take a look at this. I believe these should function as search buttons @mikewestaz please confirm

**Comment by mikewestaz** [comment]
That's correct, these should be search terms

**Comment by MartyBeckers** [comment]
That's placeholder content that employees can edit in the CMS, but I've added the links in this format: /Search/?searchtext=Rain%20Disc
