### ISSUE TITLE
Home: 'Innovating' header needs spacing adjustment

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#79]
- [ ] Recommend changing padding on ``class="innovative-header"``  to ``padding: 55px 0px;``
- [x] Adjust the space between the Innovative header and the water to be 1/2 the space (see screen shot and original comp: http://invis.io/3F2F4N1KD)

![culligan-innovates-padding](https://cloud.githubusercontent.com/assets/10550484/7073409/33b6a4ea-dea8-11e4-948a-095c549d8d9c.png)

**Comment by nickpaventi** [comment]
@mikewestaz this extra white space is coming from the image itself, should we crop to top?

**Comment by mikewestaz** [comment]
Looks like the second part of this you menioned @nickpaventi is resolved with the new photo

**Comment by nickpaventi** [comment]
N/A
