### ISSUE TITLE
Home: Font weight change needed on 'innovation' header

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#81]
The font looks like a lighter weight, even though it's also set to 800. 
Needs to look like the bold font used in the header/h1's

![innovatino-header-text](https://cloud.githubusercontent.com/assets/10550484/7075303/b9e867ee-deb5-11e4-8843-c7760061ea82.png)

**Comment by nickpaventi** [comment]
Fixed
