### ISSUE TITLE
Global Footer: Email signup refreshes page

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#84]
When signing up for the email list clicking submit should not refresh the page. The message should appear in place of the form without refresh.

@zheindel - have you/the client reviewed the message copy that is returned? See screen shot, I think we should probably revise if this isn't from the client.

![screenshot 2015-04-09 12 53 05](https://cloud.githubusercontent.com/assets/10550484/7075498/625c4246-deb7-11e4-9903-37a7f813fd06.png)

**Comment by zheindel** [comment]
@mikewestaz - Client hasn't reviewed this is just the general Kentico plugin I believe.  We can change that to whatever, just let me know or Tag Marty in here what to change that too.  Maybe Just..."Thank you for joining the mailing list!"

**Comment by mikewestaz** [comment]
@zheindel @nickpaventi  - yes, let's just remove the second sentence

**Comment by nickpaventi** [comment]
@MartyBeckers where can we remove that last sentence?

**Comment by MartyBeckers** [comment]
I removed it just now and it's located at http://dev.culligandiy.com/CMSSiteManager/ > Page templates > Culligan DIY > Culligan DIY Master > Design > sprocket next to "Mailing List Thank You"

**Comment by nickpaventi** [comment]
@mikewestaz @zheindel is this all set now?

**Comment by zheindel** [comment]
@nickpaventi Good on my side.
