### ISSUE TITLE
Global Product Listings [TABLET]: Hover causes text to shift

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#86]
At 1024 width:
Columns are off and don't flow. This might be resolved with closing JS portion of https://github.com/nickpaventi/culligan-diy/issues/63

https://www.dropbox.com/s/22n6wtlezrpxa7i/tablet-columns-off.mov?dl=0

**Comment by nickpaventi** [comment]
@mikewestaz this should be all set, please confirm.

**Comment by mikewestaz** [comment]
@nickpaventi confirmed.
