### ISSUE TITLE
Home [Tablet]: Blue dots too congested

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#89]
When in 768 view, space is too congested. Blue dots and supporting text should be hidden

![768-blue-dots](https://cloud.githubusercontent.com/assets/10550484/7076040/576d0718-debb-11e4-9e4f-18d587064323.png)

**Comment by nickpaventi** [comment]
@MartyBeckers also can't find this, but the fix is simple. Note this needs to be applied to both Blue dot sections.

OLD 
```HTML
<div class="dot-callout hide-for-small show-for-medium-up">
```
NEW
```HTML
<div class="dot-callout show-for-large-up">
```

**Comment by MartyBeckers** [comment]
Ok that change is in place and it resolved the issue.
