### ISSUE TITLE
Home [Mobile]: Header text needs adjustment

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#91]
There's an in-line style adding a large amount of padding and needs to be removed
``<div class="half-background-image" style="padding-left: 84px;">``

Also, recommend for mobile font size change to ``font-size: 45px;``

![screenshot 2015-04-09 13 26 12](https://cloud.githubusercontent.com/assets/10550484/7076127/1339b680-debc-11e4-9233-9ffc7d93e771.png)

**Comment by nickpaventi** [comment]
fixed
