### ISSUE TITLE
Home [Mobile]: Padding needed between title and tags

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#92]
The copy is removed between the title and the solution tags (correct) however need padding above the 'perfect solution...' text

add ``padding-top: 15px;``

![gap-is-missing](https://cloud.githubusercontent.com/assets/10550484/7076355/a6246e26-debd-11e4-83ba-ae758b8eb05c.png)

**Comment by nickpaventi** [comment]
fixed
