### ISSUE TITLE
Home [Mobile]: Quote attribution needs padding 

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#93]
Should be some space between the attribution and the quote

Needs ``padding-top:20px;``

![mobile-quote](https://cloud.githubusercontent.com/assets/10550484/7076463/74300f0a-debe-11e4-9682-563f6e239098.png)

**Comment by nickpaventi** [comment]
@MartyBeckers for this one I think we need to wrap the quote author in a span and then add this padding? I added the css style, can you wrap that in the span? I can't seem to find it.

**Comment by MartyBeckers** [comment]
Ok I've wrapped it in a span and that's in http://dev.culligandiy.com/CMSSiteManager/ > Development > Page Templates > Culligan DIY > Culligan DIY Home > Design > the little sprocket on "Drinking Water Quote" (it's also an editable piece of content)

**Comment by nickpaventi** [comment]
Thanks!
