### ISSUE TITLE
Global Footer [Mobile]: Links at the bottom need style adjustment

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#94]
- [x] Wrapped list needs line height increased
- [x] Spacing between Copyright and first pipe is off
- [x] Margin on the left of the list is bigger than the margin on the left of the copyright

![mobile-footer](https://cloud.githubusercontent.com/assets/10550484/7076579/461fda18-debf-11e4-8857-967b8dbc0864.png)

**Comment by nickpaventi** [comment]
fixed
