### ISSUE TITLE
Clicking on Featured Products

### ISSUE THREAD

**Issue by zheindel** [nickpaventi/culligan-diy#97]
@nickpaventi - can we make it so the whole space is clickable and not just the "View Details" of the product when you scroll over please?
![screen shot 2015-04-09 at 1 51 14 pm](https://cloud.githubusercontent.com/assets/11874973/7076694/fef75e26-debf-11e4-9cba-30050b29feb4.png)

**Comment by mikewestaz** [comment]
Closing this is a duplicate ticket
