### ISSUE TITLE
Product Category: Feature #1 tag needs adjustments

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#99]
Sample page: http://dev.culligandiy.com/Undersink-Systems

- [x] The tags need the same adjustments @nickpaventi made to the product listings to improve readability and wrapping 
- [ ] Tags need hover color change

![screenshot 2015-04-09 15 03 54](https://cloud.githubusercontent.com/assets/10550484/7077924/a6af14de-dec9-11e4-873a-5dcc48ec117f.png)

**Comment by nickpaventi** [comment]
Part 1 Fixed at line 15238

**Comment by nickpaventi** [comment]
Part 2 Added line 15241
